CONST KEYESC = &H1
CONST KEYTAB = &HF
CONST KEYSPC = &H39

CONST KEY1 = &H2
CONST KEY2 = &H3
CONST KEY3 = &H4
CONST KEY4 = &H5
CONST KEY5 = &H6
CONST KEY6 = &H7
CONST KEY7 = &H8
CONST KEY8 = &H9
CONST KEY9 = &HA
CONST KEY0 = &HB

CONST KEYLFT = &H4D
CONST KEYRGT = &H4B
CONST KEYUP = &H48
CONST KEYDWN = &H50

CONST KEYCTL = &H1D
CONST KEYALT = &H38

CONST KEYQ = &H10
CONST KEYP = &H19
CONST KEYL = &H26
CONST KEYV = &H2F

