#pragma once
#inclib "title"

DECLARE SUB TITLE_EndDemo ()
DECLARE SUB TITLE_GoodBye ()
DECLARE SUB TITLE_Intro ()
DECLARE SUB TITLE_Menu ()
DECLARE SUB TITLE_Opening ()
DECLARE SUB TITLE_ShowCredits ()
DECLARE SUB TITLE_TheEnd ()
DECLARE SUB TITLE_Ad ()
DECLARE SUB TITLE_AdTwo ()
